import esbuild from 'esbuild';
import process from 'process';
import { copyFileSync, mkdirSync, writeFileSync } from 'fs';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// Dev builds go straight into a vault (test-vault/ unless PLAINLIST_VAULT is set) so Hot Reload picks them up.
const vault = process.env.PLAINLIST_VAULT || 'test-vault';
const outdir = prod ? '.' : `${vault}/.obsidian/plugins/plainlist`;

const copyManifest = {
	name: 'copy-manifest',
	setup(build) {
		build.onEnd(() => {
			mkdirSync(outdir, { recursive: true });
			copyFileSync('manifest.json', `${outdir}/manifest.json`);
			// Tells the Hot Reload plugin to reload Plainlist when the build changes.
			writeFileSync(`${outdir}/.hotreload`, '');
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: { main: 'src/main.ts', styles: 'src/styles.css' },
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outdir,
	minify: prod,
	plugins: prod ? [] : [copyManifest],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
